### ISSUE TITLE
Only aafwall.sh created, none of the companies scripts

### ISSUE THREAD

**Issue by retakal** [mglinux/afwall_easy#2]
Hi,
I am working on ubuntu with Python 2.7.3 and py2-ipaddress 3.4.1 installed.

The script runs flawlessly without printing any errors when I select to generate blocks for the ASNs. However in the generated afwscripts folder I can only find aafwall.sh and iptables_off.sh

Any idea? How to further debug?

Big thanks for the script. It is what I am looking for!

**Comment by mglinux** [comment]
Did you use v1.3 ? You could run any Python script itself to get an error message. Guess it is related to wrong ipaddr. See readme: python2-ipaddr package is required. Guess you have the other one installed

**Comment by retakal** [comment]
Could you maybe post a link to the right module? I found a few ones...
Thanks!

**Comment by mglinux** [comment]
I use arch Linux. Here are only two packages. There should not be that much different versions. Try apt-get install python2-ipaddr

**Comment by mglinux** [comment]
Any luck with your package? Did you find the right one?

**Comment by mglinux** [comment]
Closed. Should all be clear :-)

**Comment by retakal** [comment]
Sorry for the late answer: It does now work. On my ubuntu linux there is no such package, so you need to install it directly. Initially I have installed py2-ipaddress-3.4.1 which didn't work for me.
Using the package 2.1.11 from https://pypi.python.org/pypi/ipaddr works
