### ISSUE TITLE
How to use your script on windows

### ISSUE THREAD

**Issue by jw243** [mglinux/afwall_easy#3]
Could you provide in your readme a step by step instruction on how to use your script on a windows machine? I have never used python before. Thanks.

**Comment by mglinux** [comment]
Hi. Sorry for the late reply. I don't support Windows, i don't use it. Sorry

**Comment by retakal** [comment]
Use virtual box and install linux in it. 

On December 28, 2016 9:51:12 PM GMT+01:00, Michael <notifications@github.com> wrote:
>Hi. Sorry for the late reply. I don't support Windows, i don't use it.
>Sorry
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mglinux/afwall_easy/issues/3#issuecomment-269539008

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mglinux** [comment]
You mean win in vb? Sorry not in the mood to mess around with Windows. Should be the same with Python but the script itself has to be run in a shell. You could use termux (f-froid). But it's a bit more difficult and not that comfortable

**Comment by retakal** [comment]
I mean the person who asked.. he just shall install a virtual Linux on his windows machine, e.g. ubuntu and then execute your application from there.

On December 29, 2016 5:32:08 PM GMT+01:00, Michael <notifications@github.com> wrote:
>You mean win in vb? Sorry not in the mood to mess around with Windows.
>Should be the same with Python but the script itself has to be run in a
>shell. You could use termux (f-froid). But it's a bit more difficult
>and not that comfortable
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mglinux/afwall_easy/issues/3#issuecomment-269655521

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
